// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: n0stack/storage/api/heartbeat.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// the entity is down if next_heartbeat < now
type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastHeartbeat *timestamp.Timestamp `protobuf:"bytes,1,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	NextHeartbeat *timestamp.Timestamp `protobuf:"bytes,2,opt,name=next_heartbeat,json=nextHeartbeat,proto3" json:"next_heartbeat,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_n0stack_storage_api_heartbeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_n0stack_storage_api_heartbeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_n0stack_storage_api_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetLastHeartbeat() *timestamp.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *Heartbeat) GetNextHeartbeat() *timestamp.Timestamp {
	if x != nil {
		return x.NextHeartbeat
	}
	return nil
}

var File_n0stack_storage_api_heartbeat_proto protoreflect.FileDescriptor

var file_n0stack_storage_api_heartbeat_proto_rawDesc = []byte{
	0x0a, 0x23, 0x6e, 0x30, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6e, 0x30, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x01, 0x0a, 0x09,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x41, 0x0a, 0x0e, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x6c,
	0x61, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x41, 0x0a, 0x0e,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x42,
	0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x30,
	0x73, 0x74, 0x61, 0x63, 0x6b, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_n0stack_storage_api_heartbeat_proto_rawDescOnce sync.Once
	file_n0stack_storage_api_heartbeat_proto_rawDescData = file_n0stack_storage_api_heartbeat_proto_rawDesc
)

func file_n0stack_storage_api_heartbeat_proto_rawDescGZIP() []byte {
	file_n0stack_storage_api_heartbeat_proto_rawDescOnce.Do(func() {
		file_n0stack_storage_api_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_n0stack_storage_api_heartbeat_proto_rawDescData)
	})
	return file_n0stack_storage_api_heartbeat_proto_rawDescData
}

var file_n0stack_storage_api_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_n0stack_storage_api_heartbeat_proto_goTypes = []interface{}{
	(*Heartbeat)(nil),           // 0: n0stack.storage.api.Heartbeat
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_n0stack_storage_api_heartbeat_proto_depIdxs = []int32{
	1, // 0: n0stack.storage.api.Heartbeat.last_heartbeat:type_name -> google.protobuf.Timestamp
	1, // 1: n0stack.storage.api.Heartbeat.next_heartbeat:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_n0stack_storage_api_heartbeat_proto_init() }
func file_n0stack_storage_api_heartbeat_proto_init() {
	if File_n0stack_storage_api_heartbeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_n0stack_storage_api_heartbeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_n0stack_storage_api_heartbeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_n0stack_storage_api_heartbeat_proto_goTypes,
		DependencyIndexes: file_n0stack_storage_api_heartbeat_proto_depIdxs,
		MessageInfos:      file_n0stack_storage_api_heartbeat_proto_msgTypes,
	}.Build()
	File_n0stack_storage_api_heartbeat_proto = out.File
	file_n0stack_storage_api_heartbeat_proto_rawDesc = nil
	file_n0stack_storage_api_heartbeat_proto_goTypes = nil
	file_n0stack_storage_api_heartbeat_proto_depIdxs = nil
}
